name: 'Determine env from labels'
description: 'Check Github labels and determine environment base on it'
inputs:
  envs:
    description: 'JSON with environments'
    required: true
    default: '{}'
outputs:
  env:
    description: 'Defined env from PR labels'
  isDefined:
    description: 'If env is defined or not'
runs:
  using: 'node16'
  main: 'index.js'
